### ISSUE TITLE
Postgres needs to be set up

### ISSUE THREAD

**Issue by vladionescu** [pretalx/ansible-pretalx#12]
Ideally this Ansible role would set up Postgres or provide docs on how to use another role to set up the db.

**Comment by rixx** [comment]
I disagree: pretalx can be run with postgresql, mysql, and sqlite at the very least. Enforcing postgres wouldn't be a good look. Also, the degrees of different postgres setups (starting at settings choices, ending at distributed setups) are just too much – there are postgres roles out there to handle such things, or you can use the ansible built-ins to manage postgres.

**Comment by vladionescu** [comment]
Makes sense! As an Ansible noob it took me a second to figure that out. I ended up using another role from Galaxy to manage Postgres, and that worked seamlessly.

I think it should hard fail or throw an error or something when no db is set up. I only realized this role doesn't take care of the db when Pretalx was serving 500s and I found errors in `/usr/share/..../data/logs` saying db connection was failing.

Perhaps this can be mitigated by better docs on how to use this role?

**Comment by rixx** [comment]
I'm always open for PRs with documentation, and would be very grateful for all contributions! Ansible is so tricky because it doesn't really standardise anything, because all setups are different. So chances are everybody will modify this and other ansible roles somewhat – even including nginx specific settings is arguably not very clean, and for that reason you can disable nginx integration.
